#!/usr/bin/env python

import struct
import sys
import win32print
import json


def main():
    enum_printers((4, 2))


def enum_printers(tpl):
    for i in tpl:
        try:
            printer_list = win32print.EnumPrinters(i)
            for printer in printer_list:
                message = '{"printer": ' + json.dumps(printer[2]) + '}'
                sys.stdout.write(struct.pack('I', len(message)))
                sys.stdout.write(message)
                sys.stdout.flush()

        except (IOError, RuntimeError, OSError):
            # logging.error("Unexpected error:" + sys.exc_info())
            sys.exit(1)
    sys.stdout.flush()
    sys.exit(0)


if __name__ == '__main__':
    main()
