#!/usr/bin/env python

import struct
import sys
import json
import cups


def main():
    enum_printers()


def enum_printers():
    try:
        con = cups.Connection()
        printer_list = con.getPrinters()
        # print printer_list 
        for printer in printer_list:
	    message = '{"printer": ' + json.dumps(printer) + '}'
            sys.stdout.write(struct.pack('I', len(message)))
            sys.stdout.write(message)
            sys.stdout.flush()
    except (IOError, RuntimeError, OSError):
        sys.exit(1)
    sys.stdout.flush()
    sys.exit(0)


if __name__ == '__main__':
    main()
